name: Hello world workflow222

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  hello-world:
    runs-on: [Self-hosted,Windows,X64]
    
    steps:
    - name: Print message
      run: |
        echo "Hello world"
        echo "$env:GITHUB_RUN_ID"
        Start-Sleep -Seconds 960
        echo "Bye"
        
    - name: Sync Changes to Cluster Branch
      run: |
        git checkout main
        git fetch origin
        git checkout ${{ vars.branch }}
        git pull || { echo 'Failed to pull'; exit 1; }
        git merge origin/main || { echo 'Merge conflict occurred'; exit 1; }
        git push origin ${{ vars.REGRESSION_CLUSTER_BRANCH_NAME }} || { echo 'Failed to push'; exit 1; }
        
